// <auto-generated />
using ManczakSzybura.KatalogProcesorow.DBSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManczakSzybura.KatalogProcesorow.DBSQL.Migrations
{
    [DbContext(typeof(DAOSQL))]
    partial class DAOSQLModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ManczakSzybura.KatalogProcesorow.DBSQL.CPUDBSQL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BaseClockGHz")
                        .HasColumnType("REAL");

                    b.Property<int>("Cores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SocketType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Threads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("manufacturerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("cPUs");
                });

            modelBuilder.Entity("ManczakSzybura.KatalogProcesorow.DBSQL.ManufacturerDBSQL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });
#pragma warning restore 612, 618
        }
    }
}
